### ISSUE TITLE
The russian characters are preventing a merge

### ISSUE THREAD

**Issue by 2102062** [2102062/Robovikes-Java-Test#12]
When I try to merge from the Github repository to my Git repository, the Russian Characters in Andrew's branch are breaking it.

**Comment by 2102062** [comment]
eoriueirutoerreitoieteurtieotruetro

**Comment by AndrewLaCost** [comment]
lmao github bad??

**Comment by 2302039** [comment]
oh no

**Comment by etsims** [comment]
no

**Comment by AndrewLaCost** [comment]
imagine bruh
simply could not be me

**Comment by sheep4** [comment]
cool

**Comment by Kylermallett** [comment]
TING
